//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weat.Entities.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRIGDEINGREDIENT
    {
        public short IDINGREDIENT { get; set; }
        public short IDFRIDGE { get; set; }
        public Nullable<short> QUANTITY { get; set; }
    
        public virtual FRIDGE FRIDGE { get; set; }
        public virtual INGREDIENT INGREDIENT { get; set; }
    }
}
