//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weat.Entities.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANNING
    {
        public short IDRECIPE { get; set; }
        public short IDUSER { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual RECIPE RECIPE { get; set; }
    }
}
